name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
    - name: Install
      run: npm ci
    - name: Run tests
      run: npm run test
